# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TabDataLoader.get_losses": "ClassConfusion.ipynb",
         "TfmdDL.get_losses": "ClassConfusion.ipynb",
         "ClassConfusion": "ClassConfusion.ipynb"}

modules = ["class_confusion.py"]

doc_url = "https://muellerzr.github.io/ClassConfusion/"

git_url = "https://github.com/muellerzr/ClassConfusion/tree/master/"

def custom_doc_links(name): return None
