# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TabDataLoader.get_losses": "01_data.ipynb",
         "TfmdDL.get_losses": "01_data.ipynb",
         "ClassConfusion": "03_class_confusion.ipynb"}

modules = ["data.py",
           "plot.py",
           "class_confusion.py"]

doc_url = "https://muellerzr.github.io/ClassConfusion2/"

git_url = "https://github.com/muellerzr/ClassConfusion2/tree/master/"

def custom_doc_links(name): return None
